- README.md
This library has been moved to the CLI repo. This change adds that notice to README.
> Add move to CLI notice

- README.md
- common.js
- index.js
- package-lock.json
- package.json
- toml-parser.js
- toml-parser.test.js
- yaml-parser.js
Fixes: https://github.com/netlify/cli/issues/565
> Add support for YAML config

- common.js
- package.json
Use `lodash.isPlainObject` instead of our own function.
> Use lodash.isPlainObject

- package.json
Fixes https://github.com/netlify/netlify-redirect-parser/issues/22
The version matches the one in our CLI.
I postfixed the commit message type with a `!` to denote a breaking change
> fix: add engines field

- .github/workflows/release-please.yml
- .github/workflows/workflow.yml
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
> chore: run CI in latest Node.js

- src/common.js
- src/line-parser.js
- src/line-parser.test.js
This enforces for `proxy` to be a boolean. At the moment, it can be `true`, `null` or `undefined`.
> feat!: enforce `proxy` to be a boolean

- src/common.js
This fixes how `module.exports` is used.
> chore: use `module.exports`

- package-lock.json
- package.json
- src/common.js
- src/netlify-config-parser.js
This switches from `lodash` to `is-plain-obj` so we get the TypeScript types.
> chore: use `is-plain-obj`

- src/common.js
There is some partial support for browser when it comes to URL parsing.
However, I could not find any browser consumer on GitHub. Also, some files are requiring Node.js modules (`fs`), i.e. I believe this would not work in browsers, or fail at bundle time.
This PR removes browser support since it seems like support was incomplete. Once we drop Node 8 from this module, we will be able to use the global `URL` variable anyway.
> chore!: remove browser partial support

- src/line-parser.js
This simplifies some code based on the fact that `parts` is always an array of string and does not have any `null` values.
> chore: simplify some code

- src/line-parser.js
- src/line-parser.test.js
- src/netlify-config-parser.js
- src/netlify-config-parser.test.js
This PR defaults `conditions` to an empty object when there are no conditions.
This prevents bugs in consumers accessing `conditions` assuming it exists. This also simplifies accessing it since the consumer does not need to test for `conditions` existence. Finally, this makes the return value more monomorphic, which will simplify typing.
> chore!: ensure `conditions` is always set

- src/common.js
- src/line-parser.js
- src/line-parser.test.js
- src/netlify-config-parser.js
- src/netlify-config-parser.test.js
This defaults `params` to an empty object and refactors the related logic.
> chore!: default `params` to an empty object

- src/line-parser.js
This simplifies the comment trimming logic based on the fact that: 
- Lines starting with `#` do not reach this function
- Line are already trimmed at that point
> chore: simplify comment trimming logic

- src/line-parser.js
- src/line-parser.test.js
- src/netlify-config-parser.js
- src/netlify-config-parser.test.js
`params` was renamed to `query`. The return value should use the new name.
> chore!: rename `params` to `query`

- src/line-parser.js
- src/line-parser.test.js
- src/netlify-config-parser.js
- src/netlify-config-parser.test.js
This PR defaults `headers` to an empty object when there are no headers, for the same reasons as #183.
> feat!: ensure `headers` is always set

- src/netlify-config-parser.js
`signed` has been renamed several times. The latest name is `signed` so it should have the priority.
Also, backward compatibility is slightly different depending on whether `_redirects` or `netlify.toml` is used.
> fix!: `signed` backward compatibility priority

- src/line-parser.js
- src/line-parser.test.js
- src/netlify-config-parser.js
- src/netlify-config-parser.test.js
This adds support for parsing Edge handlers location in both `_redirects` and `netlify.toml`
See https://docs.netlify.com/routing/edge-handlers/configure-and-deploy/#declare-edge-handlers
> feat: add support for parsing Edge handlers location

- src/common.js
- src/line-parser.js
- src/line-parser.test.js
- src/netlify-config-parser.js
- src/netlify-config-parser.test.js
The current code is returning error objects instead of throwing exceptions.
The main advantage is that this returns all parsing errors instead of only the first one. 
- However, in most cases, users write their configuration files (such as redirects) incrementally, not all at once, so they are unlikely to introduce many syntax errors at once. 
- Also, it is possible that several parsing errors are in fact a single one. In that case, reporting all of them would actually be detrimental. For example, if a user is using `/* */` multiline comments in `_redirects`, this is a single syntax error but might currently reported as many errors.
Instead, this PR switches to throwing exceptions instead. This has the following advantages:
- Consistency with our other projects (CLI, `@netlify/config`, …
> feat!: use exceptions

- src/netlify-config-parser.js
Non-force forward rules are allowed with `_redirects` but not with `netlify.toml`.
I have tracked down changes to this file and it seemed like this change of behavior was introduced by https://github.com/netlify/cli/pull/518. However, it looks like that PR was not not meant to do so and this is a bug.
Forbidding non-force forward rules does not seem to make sense. Also, any users currently using non-force forward rules in `netlify.toml` should experience syntax error validation, so allowing it should only improve behavior (as opposed to make currently existing sites fail).
> fix: allow non-force forward rules

- src/common.js
- src/line-parser.js
- src/netlify-config-parser.js
- tests/line-parser.js
We validate when the `from` field is missing.
However, since empty lines or lines with only comments are valid, this can only happen when using redirects in `netlify.toml` not inside `_redirects`. This PR fixes this.
> fix: validation of `from`

- src/netlify-config-parser.js
This validates that `redirects` is an array inside `netlify.toml`.
Using `[redirects]` instead of `[[redirects]]` is a likely mistake.
> feat: validate that `redirects` is an array

- src/line-parser.js
- src/netlify-config-parser.js
- tests/helpers/main.js
In #196, I misread the new syntax for Edge handlers.
Edge handlers now have their own top-level property in `netlify.toml`, i.e. should be parsed separately from redirects.
> chore: remove Edge handlers parsing

- src/line-parser.js
This is a small refactor of the logic related to statuses considering `status` cannot be `undefined` in this branch (due to the `parts.length === 0` prior validation).
> chore: simplify status parsing

- src/common.js
- src/line-parser.js
- src/netlify-config-parser.js
This removes more duplicate code by refactoring forward rules.
This applies forward rules before URL parsing, which is ok since the forward rules logic only changes the end of the string from `/*` to `/:splat` which works for both file paths and URLs.
> chore: refactor forward rules

- package-lock.json
- package.json
- src/line_parser.js
- tests/line_parser.js
Part of https://github.com/netlify/build/issues/2889
This allows the `_redirects` file to be optional.
This will be useful for `@netlify/config` so it does not need to perform that check.
> feat: allow `_redirects` to be optional

- src/index.js
- src/merge.js
- tests/merge.js
Part of https://github.com/netlify/build/issues/2889
This adds some logic to merge redirects.
The logic looks so simple one might think we should not bother. However, this provides with abstraction, allowing us to change the merging logic in a single place later. Also, just figuring out what the merging logic was took me some time, and the code comments themselves can be useful.
> feat: add logic to merge redirects

- src/common.js
- src/line_parser.js
- src/netlify_config_parser.js
- src/url.js
- tests/line_parser.js
Part of https://github.com/netlify/build/issues/2889
This separates the logic related to:
- Parsing the `_redirects` to an array with a syntax identical to the one used in `netlify.toml`
- Parsing the `netlify.toml`
- Normalizing and validating the output of both parsing
Separating those steps is needed to use this in `@netlify/config` since `@netlify/config` already performs the `netlify.toml` parsing step, but not the others.
Also, this allows more code re-use by minimizing `_redirects` and `netlify.toml` to the pure string -> object logic, without additional semantics.
> fix: separate normalization logic

- src/all.js
- src/index.js
- src/line_parser.js
- src/netlify_config_parser.js
- tests/all.js
This creates a `parseAllRedirects()` method which parses both `netlify.toml` and `_redirects`, and normalize/validate the result.
This will be used by Netlify CLI, removing some code there which is currently doing this.
> feat: add `parseAllRedirects()`

- src/merge.js
- tests/merge.js
This improves how redirects from `_redirects` and `netlify.toml` are merged:
- Add default values
- Add more validation
> feat: improve redirects merging

- tests/fixtures/netlify_config/from_no_slash.toml
- tests/fixtures/redirects_file/invalid_no_slash
- tests/line_parser.js
- tests/netlify_config_parser.js
This adds more tests related to the following point: the leading `/` in paths is optional in `netlify.toml` but not in `_redirects`.
> chore: add more tests

- src/normalize.js
- tests/all.js
- tests/line_parser.js
- tests/merge.js
- tests/netlify_config_parser.js
Fixes #265.
The `origin` field should be returned. 
It combines the `scheme`+`host`+`path` fields, which should still be returned.
> fix: add `origin` field

- src/all.js
Since https://github.com/netlify/build/pull/3242, redirects normalization is happening before redirects merging in `@netlify/config`.
This PR aligns `netlify-redirect-parser` `parseAllRedirects()` (used by `netlify dev`) with this new behavior.
> feat: align `parseAllRedirects()` order with `@netlify/config` order

- src/all.js
- src/normalize.js
- tests/all.js
- tests/fixtures/netlify_config/minimal.toml
- tests/helpers/main.js
- tests/netlify_config_parser.js
Parsing redirects adds a few properties that are used by `netlify dev`: `path`, `scheme`, `host`, `proxy`.
However, `@netlify/config` should not receive those properties since it serializes the result back to `netlify.toml` and those properties are invalid in `netlify.toml`.
This PR fixes this by adding a `minimal` boolean option to decide whether to return those properties. It defaults to returning them which is the current behavior, i.e. this is not a breaking change.
> feat: add `minimal` option

- .github/workflows/release-please.yml
Temporarily patches the `release-please` action until https://github.com/google-github-actions/release-please-action/issues/337 is fixed.
> chore: fix release process

- src/merge.js
- tests/merge.js
See background at https://github.com/netlify/build/pull/3424#discussion_r687150838
This removes duplicate headers with `mergeRedirects()`.
> feat: remove duplicates

- src/all.js
- src/line_parser.js
- src/merge.js
- src/netlify_config_parser.js
- src/normalize.js
- src/results.js
- tests/all.js
- tests/line_parser.js
- tests/merge.js
- tests/netlify_config_parser.js
In production, when a specific redirect in either `_redirects` or `netlify.toml` has some syntax error, that redirect is ignored but we still parse the other redirects. However, this library throws instead.
This PR brings the production behavior, so: 
- The CLI behavior matches it (as part of the world-class local development initiative). 
- `netlifyConfig.redirects` modifications match it (as part of https://github.com/netlify/build/issues/1193)
It does so by making all methods return an object `{ redirects, errors }` instead of a single array `redirects`. `errors` is an array of error instances.
Sibling PR for headers parsing: https://github.com/netlify/netlify-headers-parser/pull/10
> feat!: add lenient parsing

- src/all.js
- tests/all.js
Part of https://github.com/netlify/build/issues/2890
Like https://github.com/netlify/netlify-headers-parser/pull/11, but for redirects instead of headers.
This adds a `configRedirects` argument to `parseAllRedirects()` to pass headers programmatically instead of specifying a `netlify.toml` path. 
This would be useful for `@netlify/config` since it has already parsed `netlify.toml` and does not need to parse it again. This will allow `@netlify/config` to switch to using `parseAllRedirects()` instead of each method exported by `netlify-redirect-parser`.
> feat: add `configRedirects` argument to `parseAllRedirects()`

- src/all.js
- src/index.js
- src/merge.js
- src/normalize.js
- tests/all.js
- tests/line_parser.js
- tests/merge.js
- tests/netlify_config_parser.js
Now that the CLI and `@netlify/config` only uses the `parseAllRedirects()` method (see https://github.com/netlify/build/pull/3475), we can export only that method. This will simplify maintaining this module and will keep its API smaller.
Sibling PR for headers: https://github.com/netlify/netlify-headers-parser/pull/13
> feat!: simplify exported methods

- renovate.json5
`path-exists@v5` requires ESM and Node 12.
> chore: add `path-exists` to `renovate.json5`

- src/line_parser.js
- tests/line_parser.js
We should handle the case where `_redirects` is a directory (which is invalid).
Sibling PR for headers: https://github.com/netlify/netlify-headers-parser/pull/26
> fix: handle `_redirects` with wrong file type

- src/line_parser.js
- src/normalize.js
- src/status.js
- tests/fixtures/netlify_config/invalid_status_empty.toml
- tests/fixtures/netlify_config/invalid_status_high.toml
- tests/fixtures/netlify_config/invalid_status_negative.toml
- tests/fixtures/netlify_config/invalid_status_string.toml
- tests/fixtures/netlify_config/status_string.toml
- tests/fixtures/redirects_file/invalid_status
- tests/line_parser.js
- tests/netlify_config_parser.js
Fixes https://github.com/netlify/build/issues/4138
This normalizes and validates the status field of redirects in both `_redirects` and `netlify.toml`.
---
> fix: normalize and validate status code

- src/all.js
- src/line_parser.js
- src/normalize.js
- src/status.js
- tests/helpers/main.js
- tests/netlify_config_parser.js
Related to https://github.com/netlify/build/pull/4184
https://github.com/netlify/netlify-redirect-parser/pull/419 added some logic to better validate when users either:
- Add a `status` field in `netlify.toml` that is invalid, e.g. it is a string instead of being a number
- Forget that the third parameter of a `_redirect`'s line should be the status
Before that PR, those errors were leading to `status` being parsed as `NaN`, which gave confusing error messages to users.
However, by making validation stricter, that PR come with some potential risk. Therefore, this current PR is adding some feature flags to it so we can progressively enable and monitor it.
Additionally, it removes the new validation logic which was added to forbid statuses below 100 or above 599.
Note: due to implementation …
> fix: add feature flags to new status normalization logic

- src/all.js
- src/line_parser.js
- src/normalize.js
- tests/helpers/main.js
This removes the `redirects_parser_normalize_status` now that it has been rolled out at 100%.
---
> fix: remove feature flag `redirects_parser_normalize_status`
