netlify/netlify-redirect-parser

netlify-config-parser.js
package-lock.json
package.json

This upgrades `@netlify/config` to its latest version.
The tests are currently failing. Once they pass, could you please make sure this PR does not break them? Thanks!

Upgrade `@netlify/config`

---

.github/workflows/release-please.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
package-lock.json
package.json

chore: add release please

---

.github/workflows/workflow.yml
package.json

Updates our CI to run on Node.js 15

chore: run CI using Node.js 15

---

.github/workflows/fossa.yml
.github/workflows/release-please.yml
.github/workflows/workflow.yml
CONTRIBUTING.md
renovate.json5

Preparing for the branch rename

chore: rename default branch from master to main

---

src/common.js

This applies some changes from Prettier.

chore: fix Prettier

---

src/line-parser.js

This is a small refactoring of a function. This does not change behavior.

chore: small refactoring

---

src/netlify-config-parser.js
src/netlify-config-parser.test.js

feat!: enforce `proxy` to be a boolean everywhere

---

src/line-parser.js

This destructures imports, which will make it easier when using ES modules in the future, and make dependencies tracking clearer.

chore: destructure imports

---

src/line-parser.js

chore: simplify some code

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This moves code that is not common out of the `common` directory.

chore: move common code

---

src/line-parser.js
src/line-parser.test.js
src/netlify-config-parser.test.js

This enforces that the returned `force` to always be a boolean.

feat!: enforce `force` to be a boolean

---

package-lock.json
package.json
src/netlify-config-parser.js

This simplifies the logic related to redirect parsing.

chore: simplify redirect parsing

---

src/line-parser.js
src/netlify-config-parser.js

This is a small performance improvement.

chore: small performance improvement

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This is some refactoring which removes some duplicated logic.

chore: share more code between both main files

---

src/line-parser.js

This refactors some parsing logic.

chore: refactor some parsing logic

---

src/line-parser.js
src/netlify-config-parser.js

Small refactoring of the spat logic.

chore: refactor splat logic

---

README.md

This improves the documentation.

feat: improve `README.md`

---

src/index.js
src/line-parser.js
src/line-parser.test.js
src/netlify-config-parser.js
src/netlify-config-parser.test.js

This makes imports and exports clearer.

chore: fix imports and exports

---

.eslintrc.js
package.json
src/line-parser.js

This fixes the linting configuration.

Fixes linting

---

src/common.js
src/line-parser.js

This simplifies some URL-related logic and make it more performant.

chore: simplify URL-related logic

---

src/line-parser.js
src/netlify-config-parser.js

This removes some duplicated logic.

chore: remove duplicated logic

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This adds more error messages describing common errors in redirects configuration.

feat: improve error handling

---

.eslintrc.js
src/common.js
src/line-parser.js
src/netlify-config-parser.js

This fixes the `func-style` linting rule.

chore: fix `func-style` linting rule

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This re-orders lines of code.
This only moves lines, this does not change any of them.

chore: re-order lines

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This removes some duplicate code.

chore: remove duplicate code

---

tests/line-parser.js
tests/netlify-config-parser.js

This removes some duplicated code in tests.

chore: remove duplicated code in tests

---

tests/fixtures/absolute_country_redirects
tests/line-parser.js

This makes some tests more uniform with each other.
This will allow introducing some test helpers to simplify testing in a follow-up PR.

chore: make tests more uniform

---

package-lock.json
package.json
tests/helpers/main.js
tests/line-parser.js
tests/netlify-config-parser.js

This uses data-driven testing.
This makes it easier to add new tests and look at existing ones, since it reduces the test to simple input (fixture) -> expected output.

chore: use data-driven testing

---

src/common.js

This moves a few lines to where they are being used.

chore: move a few lines

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This removes some duplicated code.

chore: remove duplicated code

---

src/line-parser.js
src/netlify-config-parser.js

This refactors the logic related to forward rules

chore: refactor forward rules

---

src/line-parser.js
src/netlify-config-parser.js

chore: renames some variables

---

src/line-parser.js

chore: rename variables

---

src/line-parser.js

chore: simplify code

---

src/line-parser.js
src/netlify-config-parser.js

This reorder some fields so they follow the order in `_redirects`.

chore: reorder fields

---

src/common.js
src/line-parser.js
src/netlify-config-parser.js

This adds all the comments which I wished had already been there :)

chore: add comments

---

LICENSE

chore: add `LICENSE` file

---

.eslintrc.js
tests/line_parser.js

chore: improve linting

---

README.md
codecov.yml

chore: add test coverage

---

renovate.json5

Should close https://github.com/netlify/netlify-redirect-parser/pull/233

chore(deps): add allowed versions for renovate

---

tests/fixtures/redirects_file/invalid_no_to_query
tests/line_parser.js

chore: add 100% test coverage

---

src/line_parser.js
tests/line_parser.js

This improves an error message.

feat: improve error message

---

renovate.json5

Closes https://github.com/netlify/netlify-redirect-parser/pull/284

chore(deps): ignore test-each updates for versions >=3

---

.github/workflows/workflow.yml
package.json
renovate.json5

This drops support for Node 8.

chore!: drop support for Node 8

---

.github/.kodiak.toml

Configures Kodiak to auto merge renovate minor and patch PRs

chore(kodiak): auto merge renovate minor and patch PRs

---

.github/workflows/release-please.yml

Reverts https://github.com/netlify/netlify-redirect-parser/pull/302 now that the bug in release please was fixed

chore: use release please v2

---

.github/PULL_REQUEST_TEMPLATE.md

CI tests are not enforced for this repo, hence the previous PR was merged.

chore: format PR template

---

.eslintrc.cjs

This PR switches to the new ESM-specific ESLint shared configuration.
---

chore: use ESM-specific ESLint config

---

renovate.json5

Part of https://github.com/netlify/team-dev/issues/36
This uses our new Renovate configuration specific for repositories which have migrated to pure ES modules.
---

chore: use ESM-specific Renovate configuration

---

src/status.js

This adds a small code comment.
---

chore: add comment for statuses with `!`
